sudo: required

services:
  - docker

before_install:
  - docker build -t dev142/react-base-app -f Dockerfile.dev .

script:
  - docker run -e CI=true dev142/react-base-app npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "aws-react-app"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-597897118064"
    bucket_path: "docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
